### ISSUE TITLE
`ValueError`: file does not contain alignment data

### ISSUE THREAD

**Issue by bounlu** [SciLifeLab/TIDDIT#109]
I got the below error. It seems the error arises from `read_contigs` step. I suspect it might be due to non-canonical chromosomes. Any thought what could be the problem and how to fix?

```
$ tiddit --sv \
--threads $threads \
--ref $mount_dir/genome.fa \
--bam $mount_dir/$out_dir/biscuit/$normal_bam \
-o $mount_dir/$out_dir/tiddit/LC_AC00

LIBRARY STATISTICS
	Pair orientation = Forward-Reverse
	Average Read length = 150.0
	Average insert size = -10541.058613317655
	Stdev insert size = 1159626.655535344
	99.95 percentile insert size = 557.0

Collecting signals on contig: chr16_KI270728v1_random
Collecting signals on contig: chr17
Collecting signals on contig: chr1_KI270707v1_random
Collecting signals on contig: chr14_KI270724v1_random
Collecting signals on contig: chr1_KI270708v1_random
Collecting signals on contig: chr14_KI270723v1_random
Collecting signals on contig: chr1_KI270710v1_random
Collecting signals on contig: chr14_GL000009v2_random
Collecting signals on contig: chr15_KI270727v1_random
Collecting signals on contig: chr14
Collecting signals on contig: chr10
Collecting signals on contig: chr14_KI270726v1_random
Collecting signals on contig: chr1_KI270706v1_random
Collecting signals on contig: chr15
Collecting signals on contig: chr17_GL000205v2_random
Collecting signals on contig: chr14_KI270725v1_random
Collecting signals on contig: chr18
Collecting signals on contig: chr11_KI270721v1_random
Collecting signals on contig: chr14_GL000194v1_random
Collecting signals on contig: chr16
Collecting signals on contig: chr14_KI270722v1_random
Collecting signals on contig: chr1_KI270712v1_random
Collecting signals on contig: chr1_KI270709v1_random
Collecting signals on contig: chr12
Collecting signals on contig: chr14_GL000225v1_random
Collecting signals on contig: chr19
Collecting signals on contig: chr13
Collecting signals on contig: chr1
Collecting signals on contig: chr1_KI270711v1_random
Collecting signals on contig: chr17_KI270730v1_random
Collecting signals on contig: chr17_KI270729v1_random
Collecting signals on contig: chr11
Collecting signals on contig: chr1_KI270713v1_random
Collecting signals on contig: chr1_KI270714v1_random
Collecting signals on contig: chr2
Collecting signals on contig: chr20
Collecting signals on contig: chr21
Collecting signals on contig: chr22
Collecting signals on contig: chr22_KI270731v1_random
Collecting signals on contig: chr22_KI270732v1_random
Collecting signals on contig: chr22_KI270733v1_random
Collecting signals on contig: chr22_KI270734v1_random
Collecting signals on contig: chr22_KI270735v1_random
Collecting signals on contig: chr22_KI270736v1_random
Collecting signals on contig: chr22_KI270737v1_random
Collecting signals on contig: chr22_KI270738v1_random
Collecting signals on contig: chr22_KI270739v1_random
Collecting signals on contig: chr2_KI270715v1_random
Collecting signals on contig: chr2_KI270716v1_random
Collecting signals on contig: chr3
Collecting signals on contig: chr3_GL000221v1_random
Collecting signals on contig: chr4
Collecting signals on contig: chr4_GL000008v2_random
Collecting signals on contig: chr5
Collecting signals on contig: chr5_GL000208v1_random
Collecting signals on contig: chr6
Collecting signals on contig: chr7
Collecting signals on contig: chr8
Collecting signals on contig: chr9
Collecting signals on contig: chr9_KI270717v1_random
Collecting signals on contig: chr9_KI270718v1_random
Collecting signals on contig: chr9_KI270719v1_random
Collecting signals on contig: chr9_KI270720v1_random
Collecting signals on contig: chrEBV
Collecting signals on contig: chrM
Collecting signals on contig: chrUn_GL000195v1
Collecting signals on contig: chrUn_GL000213v1
Collecting signals on contig: chrUn_GL000214v1
Collecting signals on contig: chrUn_GL000216v2
Collecting signals on contig: chrUn_GL000218v1
Collecting signals on contig: chrUn_GL000219v1
Collecting signals on contig: chrUn_GL000220v1
Collecting signals on contig: chrUn_GL000224v1
Collecting signals on contig: chrUn_GL000226v1
Collecting signals on contig: chrUn_KI270311v1
Collecting signals on contig: chrUn_KI270317v1
Collecting signals on contig: chrUn_KI270322v1
Collecting signals on contig: chrUn_KI270435v1
Collecting signals on contig: chrUn_KI270438v1
Collecting signals on contig: chrUn_KI270442v1
Collecting signals on contig: chrUn_KI270512v1
Collecting signals on contig: chrUn_KI270519v1
Collecting signals on contig: chrUn_KI270538v1
Collecting signals on contig: chrUn_KI270579v1
Collecting signals on contig: chrUn_KI270589v1
Collecting signals on contig: chrUn_KI270741v1
Collecting signals on contig: chrUn_KI270742v1
Collecting signals on contig: chrUn_KI270743v1
Collecting signals on contig: chrUn_KI270744v1
Collecting signals on contig: chrUn_KI270745v1
Collecting signals on contig: chrUn_KI270746v1
Collecting signals on contig: chrUn_KI270747v1
Collecting signals on contig: chrUn_KI270748v1
Collecting signals on contig: chrUn_KI270749v1
Collecting signals on contig: chrUn_KI270750v1
Collecting signals on contig: chrUn_KI270751v1
Collecting signals on contig: chrUn_KI270752v1
Collecting signals on contig: chrUn_KI270753v1
Collecting signals on contig: chrUn_KI270754v1
Collecting signals on contig: chrUn_KI270755v1
Collecting signals on contig: chrUn_KI270756v1
Collecting signals on contig: chrUn_KI270757v1
Collecting signals on contig: chrX
Collecting signals on contig: chrY
Collecting signals on contig: chrY_KI270740v1_random
total 310.280535697937
Writing signals to file
extracted signals in:
-330.81649899482727
/opt/conda/envs/tiddit/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/conda/envs/tiddit/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
calculated coverage in:
125.14846658706665
[M::main_ropebwt2] inserted 226699924 symbols in 17.377 sec, 40.176 CPU sec
[M::main_ropebwt2] constructed FM-index in 17.902 sec, 40.701 CPU sec
[M::main_ropebwt2] symbol counts: ($, A, C, G, T, N) = (1501324, 85186519, 27412781, 27412781, 85186519, 0)
[M::main_ropebwt2] rld: (tot, $, A, C, G, T, N) = (226699924, 1501324, 85186519, 27412781, 27412781, 85186519, 0)
[M::main] Version: r187
[M::main] CMD: ropebwt2 -dNCr /data/omeran/sv_calling/tiddit/LC_AC00_tiddit/clips.fa
[M::main] Real time: 18.806 sec; CPU: 41.556 sec
[M::fm6_unitig] choose prime 123457
[M::main] Version: r178
[M::main] CMD: fermi2 assemble -t 32 -l 81 -
[M::main] Real time: 25.227 sec; CPU: 202.571 sec
Traceback (most recent call last):
  File "/opt/conda/envs/tiddit/bin/tiddit", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/envs/tiddit/lib/python3.10/site-packages/tiddit/__main__.py", line 148, in main
    tiddit_contig_analysis.main(prefix,sample_id,library,contigs,coverage_data,args)
  File "tiddit/tiddit_contig_analysis.pyx", line 134, in tiddit.tiddit_contig_analysis.main
  File "tiddit/tiddit_contig_analysis.pyx", line 11, in tiddit.tiddit_contig_analysis.read_contigs
  File "pysam/libcalignmentfile.pyx", line 747, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 952, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file does not contain alignment data
```

**Comment by bounlu** [comment]
It turned out to be the `bwa` step failed due to the lack of index, causing `read_contigs` to fail subsequently on the empty `sam` file. Since the standard error is sent `/dev/null`, failure on bwa was not printed in the log output, and the empty sam file was still generated. I think a checkpoint at these steps would be useful to implement.

**Comment by J35P312** [comment]
Hello!
And sorry for slow reply! I Just came back from vacation. Happy to hear that it worked out for you! I will look into this, I agree some checkpoint or proper warning would be useful
//Jesper
