### ISSUE TITLE
QUAL missing

### ISSUE THREAD

**Issue by fgvieira** [SciLifeLab/TIDDIT#96]
Dear all,
is there a reason with SVs called by TIDDIT do not have a QUAL value?
Would it make sense to use [SVtyper](https://github.com/hall-lab/svtyper)?

**Comment by J35P312** [comment]
Hello!
No good reason ;P.
There used to be a Qual value, but it "disapeared" when updating to 3.0.0! I will consider adding it again!
Meanwhile, feel free to try SVtyper or paragraph (https://github.com/Illumina/paragraph)

**Comment by fgvieira** [comment]
I tried SVtyper but got an error. Is tiddit supposed to work with SVtyper?

**Comment by J35P312** [comment]
Though luck! I have not tried SVtyper in a long while! Hence im not sure.
Back when I did, it only worked on Lumpy. What error did you get? If the error is reasonable I can fix it, but if it assumes lumpy vcf I will not.

**Comment by fgvieira** [comment]
I got this error:
```
$ svtyper -B $GERMLINE_BAM -i $PrefixName_vcf > test
Traceback (most recent call last):
  File "/services/tools/anaconda2/4.4.0/bin/svtyper", line 10, in <module>
    sys.exit(cli())
  File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/svtyper/classic.py", line 575, in cli
    sys.exit(main())
  File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/svtyper/classic.py", line 568, in main
    args.max_ci_dist)
  File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/svtyper/classic.py", line 234, in sv_genotype
    if [var.info](http://var.info/)['MATEID'] in breakend_dict:
KeyError: 'MATEID'
```

**Comment by J35P312** [comment]
Though luck! But thanks for trying!  I also tried a file with no BND, but then it crashed on CIPOS instead:

  File "/usr/local/lib/python2.7/site-packages/svtyper/classic.py", line 265, in sv_genotype
    ciA = confidence_interval(var, 'CIPOS', 'CIPOS95', max_ci_dist)
  File "/usr/local/lib/python2.7/site-packages/svtyper/parsers.py", line 12, in confidence_interval
    ci = map(int, var.info[tag].split(','))

i.e it will probably not be possible to make tiddit run with svtyper. I will continue working on adding a quality score!
